// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAx7fxeoxbR5PCNDX3YgIfPX97YmeVzLQ',
    appId: '1:448561284573:web:6acc2fbb18d123f3f52234',
    messagingSenderId: '448561284573',
    projectId: 'innerscape-f10ac',
    authDomain: 'innerscape-f10ac.firebaseapp.com',
    storageBucket: 'innerscape-f10ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrHosSAC6OWuqpU6MWN41oNCKJlldCXvE',
    appId: '1:448561284573:android:c207f0be73b6c69df52234',
    messagingSenderId: '448561284573',
    projectId: 'innerscape-f10ac',
    storageBucket: 'innerscape-f10ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWtqkQszPF6C1WbQWBdzzuqrtuyIIhXjk',
    appId: '1:448561284573:ios:d4e1a6a27fe0cf5bf52234',
    messagingSenderId: '448561284573',
    projectId: 'innerscape-f10ac',
    storageBucket: 'innerscape-f10ac.firebasestorage.app',
    iosBundleId: 'com.example.innerscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWtqkQszPF6C1WbQWBdzzuqrtuyIIhXjk',
    appId: '1:448561284573:ios:d4e1a6a27fe0cf5bf52234',
    messagingSenderId: '448561284573',
    projectId: 'innerscape-f10ac',
    storageBucket: 'innerscape-f10ac.firebasestorage.app',
    iosBundleId: 'com.example.innerscape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAx7fxeoxbR5PCNDX3YgIfPX97YmeVzLQ',
    appId: '1:448561284573:web:a1193fdcfb06a391f52234',
    messagingSenderId: '448561284573',
    projectId: 'innerscape-f10ac',
    authDomain: 'innerscape-f10ac.firebaseapp.com',
    storageBucket: 'innerscape-f10ac.firebasestorage.app',
  );

}